dataset :
    name : "crate"
    type : "ndds"
    device : "gpu"
    model_dir : "/media/aditya/A69AFABA9AFA85D9/Datasets/roman/models"
    image_dir : "/media/aditya/A69AFABA9AFA85D9/Cruzr/code/Dataset_Synthesizer/Test/Zed/Final"
    perch_debug_dir : "/media/aditya/A69AFABA9AFA85D9/Cruzr/code/DOPE/catkin_ws/src/perception/sbpl_perception/visualization"
    python_debug_dir : "./model_3dof"
python2_paths :
  - '/opt/ros/kinetic/lib/python2.7/dist-packages'
  - '/usr/local/lib/python2.7/dist-packages/'
  - '/media/aditya/A69AFABA9AFA85D9/Cruzr/code/DOPE/catkin_ws/devel/lib/python2.7/dist-packages'
python3_paths :
  - '/media/aditya/A69AFABA9AFA85D9/Cruzr/code/ros_python3_ws/devel/lib/python3/dist-packages'
analysis:
  output_dir : "./crate_analysis_output"
  device :
    icp:
      result_files:
        accuracy :
          - '/media/aditya/A69AFABA9AFA85D9/Cruzr/code/YCB_Video_toolbox/3dof_exp/crate/accuracy_icp.txt'
        runtime :
          - '/media/aditya/A69AFABA9AFA85D9/Cruzr/code/YCB_Video_toolbox/3dof_exp/crate/runtime_icp.txt'
    gpu:
      result_files:
        accuracy :
          - '/media/aditya/A69AFABA9AFA85D9/Cruzr/code/YCB_Video_toolbox/3dof_exp/crate/accuracy_gpu_full_psc_24_minn_65.txt'
        runtime :
          - '/media/aditya/A69AFABA9AFA85D9/Cruzr/code/YCB_Video_toolbox/3dof_exp/crate/runtime_gpu_full_psc_24_minn_65.txt'
    cpu:
      result_files:
        accuracy :
          - '/media/aditya/A69AFABA9AFA85D9/Cruzr/code/YCB_Video_toolbox/3dof_exp/crate/accuracy_cpu_full_minn_75.txt'
        runtime :
          - '/media/aditya/A69AFABA9AFA85D9/Cruzr/code/YCB_Video_toolbox/3dof_exp/crate/runtime_cpu_full_minn_75.txt'
