search_resolution_translation: 0.08 # m 0.04
search_resolution_yaw: 0.3926991 # rad
x_min : 0.96
x_max : 1.0
y_min : -0.20
y_max : 0.20
table_height : 0.00
use_external_render : 0

perch_params:
  sensor_resolution_radius: 0.003 #m
  min_neighbor_points_for_valid_pose: 500 #50
  max_icp_iterations: 20
  icp_max_correspondence: 0.05 #m #0.075
  use_adaptive_resolution: false
  use_rcnn_heuristic: false
  use_model_specific_search_resolution: false

  ## Visualization and Debugging
  visualize_expanded_states: true
  print_expanded_states: true
  debug_verbose: false # unused

  ## Clutter mode
  use_clutter_mode: false
  # Should be in [0,1], unused if use_clutter_mode is false
  clutter_regularizer: 1
