# Used for conveyor dataset
search_resolution_translation: 0.07 # m 0.04
# search_resolution_yaw: 0.2526991 # rad
search_resolution_yaw: 0.4 # rad
# use_external_render : 0
# use_external_pose_list : 0
# use_icp : 1
# use_full_object_point_cloud: true

perch_params:
  min_points_for_constraint_cloud: 50
  max_icp_iterations: 40
  icp_max_correspondence: 0.05 #m #0.075
  use_adaptive_resolution: false
  use_rcnn_heuristic: false
  use_model_specific_search_resolution: false
  depth_median_blur: 9

  ## RGB
  use_color_cost: false
  color_distance_threshold: 15

  ## With Downsampling
  use_downsampling: true
  sensor_resolution_radius: 0.015
  # sensor_resolution_radius: 0.005 #m
  min_neighbor_points_for_valid_pose: 60 #mustard,sugar,drill
  # min_neighbor_points_for_valid_pose: 40 #soup
  downsampling_leaf_size: 0.015
  # downsampling_leaf_size: 0.01

  ## Without Downsampling
  # sensor_resolution_radius: 0.003 #m
  # min_neighbor_points_for_valid_pose: 500 #50

  ## Clutter mode
  use_clutter_mode: false
  # Should be in [0,1]
  clutter_regularizer: 0.1

  ## GPU stuff
  use_gpu: false
  gpu_batch_size: 700
  gpu_stride: 4
  use_cylinder_observed: true
  gpu_occlusion_threshold: 1.0 #cm, used when no segmentation


  ## Visualization and Debugging
  visualize_expanded_states: false
  visualize_successors: false
  print_expanded_states: false
  debug_verbose: false # unused
