# search_resolution_translation: 0.05 # m 0.04
# search_resolution_yaw: 0.3926991 # rad
# use_external_render : 0
# use_full_object_point_cloud: true
# for 6D

perch_params:
  min_points_for_constraint_cloud: 50
  # max_icp_iterations: 200 #For fast_vgicp
  max_icp_iterations: 150 #For fast_gicp
  icp_max_correspondence: 0.05 #m #0.075
  use_adaptive_resolution: false
  use_rcnn_heuristic: false
  use_model_specific_search_resolution: false
  icp_type: 3 #GICP CUDA - 2, GICP CPU - 1,  Fully integrated GICP CUDA - 3

  ## RGB
  use_color_cost: false
  color_distance_threshold: 15.0

  ## With Downsampling
  use_downsampling: true
  # sensor_resolution_radius: 0.015 #m
  sensor_resolution_radius: 0.01 #m gpu-stride : 5
  # min_neighbor_points_for_valid_pose: 20 #clutter
  min_neighbor_points_for_valid_pose: 30 #tower
  # downsampling_leaf_size: 0.02
  downsampling_leaf_size: 0.01

  ## Without Downsampling
  # sensor_resolution_radius: 0.003 #m
  # min_neighbor_points_for_valid_pose: 500 #50

  ## Clutter mode
  use_clutter_mode: false
  # Should be in [0,1]
  clutter_regularizer: 0.1

  ## GPU stuff
  use_gpu: true
  gpu_batch_size: 700
  gpu_stride: 8

  ## Visualization and Debugging
  visualize_expanded_states: false
  visualize_successors: false
  print_expanded_states: false
  debug_verbose: false # unused
