search_resolution_translation: 0.07 # m 0.04
search_resolution_yaw: 0.4 # rad
mesh_in_mm: false
mesh_scaling_factor: 1

# Below for soda data
# mesh_in_mm: true
# mesh_scaling_factor: 0.6

perch_params:
  min_points_for_constraint_cloud: 50
  max_icp_iterations: 15
  icp_max_correspondence: 0.05 #m #0.075
  use_adaptive_resolution: false
  use_rcnn_heuristic: false
  use_model_specific_search_resolution: false

  ## RGB
  use_color_cost: true
  color_distance_threshold: 15

  ## With Downsampling
  use_downsampling: true
  sensor_resolution_radius: 0.0075 #m
  min_neighbor_points_for_valid_pose: 30 #50
  downsampling_leaf_size: 0.0075

  ## GPU stuff
  use_gpu: true
  gpu_batch_size: 500

  ## Clutter mode
  use_clutter_mode: false
  # Should be in [0,1]
  clutter_regularizer: 0.1

  ## Visualization and Debugging
  visualize_expanded_states: true
  visualize_successors: false
  print_expanded_states: false
  debug_verbose: false # unused
